# Local run unit tests
# for docker-compose CLI like this manual https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/
#
# Important: run `composer install` before first time use
# docker-compose run --rm --entrypoint composer php update --no-dev -vvv
#
# run directly (can't terminate)
# docker-compose  run --rm --entrypoint /repo/vendor/bin/phpunit php
#
# use shell
# docker-compose run --rm --entrypoint bash php
# /repo/vendor/bin/phpunit

version: '2'
services:
  php:
    image: bscheshir/codeception:php7.2.12-fpm-alpine-yii2 #contain phpunit
    volumes:
      - .:/var/www/html #src and tests shared to container
      - ~/.composer/cache:/root/.composer/cache
    environment:
      TZ: Europe/Moscow
      XDEBUG_CONFIG: "remote_host=${DEV_REMOTE_HOST} remote_port=${DEV_REMOTE_PORT} var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME}"
